spring:
  security:
    user:
      name: root
      password: pass123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/virgo
    username: root
    password: password
  jpa:
    properties.hibernate: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update